#app
server:
    port: 8602

#spring
spring:
  thymeleaf:
    cache: true   #关闭缓存
  devtools:
    restart:
      enabled: true #启动热部署
      additional-paths:
      - src/main/java #设置重启的目录，添加哪个目录文件需要restart

