server:
  port: 8605
spring:
  application:
    name: mogu_search
  jmx:
    default-domain: mogu_search
  security:
    user:
      name: user
      password: password123
  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: localhost:9300
    solr:
      host: http://localhost:8080/solr
      core: collection1
      repositories:
        enabled: true

  #  jackson:
  #    default-property-inclusion: non_null
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8606
        username: user
        password: password123

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always