server:
  port: 8605
spring:
  application:
    name: mogu_configuration
  cloud:
    bus:      enabled: true
      trace:        enabled: true
    config:
      server:
        git:
          uri: https://gitee.com/HuoXuYeWuSuoWei/mogu_configuration.git
  rabbitmq:
    host: 127.0.0.1 #rabbitmq的主机ip
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh